// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RitzpaStockExchange.Data;

#nullable disable

namespace RitzpaStockExchange.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230618135246_AddedUserEntity")]
    partial class AddedUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Command", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BuyStockName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommandType")
                        .HasColumnType("int");

                    b.Property<int>("CommandWay")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStockRate")
                        .HasColumnType("int");

                    b.Property<string>("SellStockName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("BuyStockName");

                    b.HasIndex("SellStockName");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Stock", b =>
                {
                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TradeCycle")
                        .HasColumnType("int");

                    b.HasKey("StockName");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockName");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RseHoldings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Command", b =>
                {
                    b.HasOne("Ritzpa_Stock_Exchange.Models.Stock", "BuyStock")
                        .WithMany("Buys")
                        .HasForeignKey("BuyStockName");

                    b.HasOne("Ritzpa_Stock_Exchange.Models.Stock", "SellStock")
                        .WithMany("Sells")
                        .HasForeignKey("SellStockName");

                    b.Navigation("BuyStock");

                    b.Navigation("SellStock");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Trade", b =>
                {
                    b.HasOne("Ritzpa_Stock_Exchange.Models.Stock", "Stock")
                        .WithMany("Trades")
                        .HasForeignKey("StockName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Ritzpa_Stock_Exchange.Models.Stock", b =>
                {
                    b.Navigation("Buys");

                    b.Navigation("Sells");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
